### ISSUE TITLE
Severely bad performance on MacOS

### ISSUE THREAD

**Issue by ginsane1** [VaporousCreeper/BetterDiscord-ThemesAndPlugins#36] opened 2019-02-01 10:04 UTC
Severely bad performance on MacOS

Unban

**Comment by starwobble** [comment] 2019-02-01 10:09
i got the same performance on mac0s 

its strange because i dont own a mac??

unban

**Comment by VaporousCreeper** [comment] 2019-02-01 14:40
You need to be specific on what you're using. Just a 'Bad performance on MacOS' isn't going to cut it.

**Comment by BradF-99** [comment] 2019-02-01 16:10
I am not seeing too much of a slowdown, I think it is caused by BetterDiscord itself - things like opening and closing modals and menus seem to be slightly slower but I am unsure if it is this theme. Is it possible to add a margin between the close / maximise / minimise buttons, and the content of the settings / server list or whatever else may be there? 

<img width="3360" alt="screen shot 2019-02-02 at 2 01 54 am" src="https://user-images.githubusercontent.com/37586752/52134283-f3dbf180-268e-11e9-8a83-8c72b46df247.png">

System specs:
MacBook Pro (15-inch, 2017) with 3.1 GHz Intel Core i7, 16GB of RAM, Radeon Pro 560 and 1TB PCI-e SSD
macOS Mojave 10.14.3 Beta (18D39a)
BetterDiscord v0.3.0
BandagedBetterDiscord v0.2.7
Discord 0.0.254

Hopefully this is specific enough to help you !

**Comment by starwobble** [comment] 2019-02-01 16:14
thats cool and all but can we get a eta on emts unban

**Comment by ginsane1** [comment] 2019-02-02 01:15
I refuse to elaborate further as I believe the root of this issue is beyond your technical ability.

Thanks,

Unban

**Comment by VaporousCreeper** [comment] 2019-02-02 02:14
It appears that Brad shows that the theme doesn't cause any fps issues.

**Closed by VaporousCreeper** 2019-02-02 02:14 UTC
Labels: low detailed
